Repository r-Techsupport/TechSupportBot, pull requests merged in 2023-05, with the labels that each got.

#349 Don't allow code blocks in stack traces
  techsupport_bot/botlogging/logger.py
Labels: Next prod update

#353 Fix DB creation bug
  techsupport_bot/base/cogs.py
  techsupport_bot/bot.py
Labels: bug, Next prod update

#336 No more silent success, and blacklist roles for setting notes
  techsupport_bot/extensions/who.py
Labels: Extension: Who, Config Changes, Next prod update

#388 Add more & better format pylint exclude
  .pylintrc
Labels: testing

#382 Create TestCases.md
  Documentation/TestCases.md
Labels: documentation
